baseURL = 'https://danielims.github.io/pymaxmusic'
languageCode = 'en-us'
title = 'PyMaxMusic'
theme = "hugo-theme-learn"
publishDir = '../docs'

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
landingPageURL='https://danielims.github.io/pymaxmusic/'
isMultiLingual=true
themeVariant = "blue"

disableLandingPageButton = true

